### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by dmachat** [alleyinteractive/sasslint-loader#3]
After #2 has been resolved and the loader is functionally stable, publish to npm for easier usage.

**Comment by natorojr** [comment]
:+1:  Please publish to `npm`

**Comment by dmachat** [comment]
I'm actually holding this back due to #4 at this point. The linter is not all that helpful without pointing to line number in source files.

**Comment by natorojr** [comment]
Okay, I'll keep an eye out on this and #4. Thanks for your contributions.

**Comment by gitnik** [comment]
I've forked this repo and published a temporary version on NPM for those who need it. Name is `temp-sasslint-loader`

**Comment by dmachat** [comment]
Hrm, if it's helpful to people without line numbers, I'm happy to at least make it available. I've published and added a note in the readme about the current state of development. Thanks @gitnik

**Comment by gitnik** [comment]
Well that means I can remove my temp package then :)
