### ISSUE TITLE
Enable full import tree for sass-lint

### ISSUE THREAD

**Issue by dmachat** [alleyinteractive/sasslint-loader#4]
Webpack only knows about the current resource, so we need to get the whole tree from the filesystem.

**Comment by ypt** [comment]
@dmachat, I just came across this same issue. Have you been able to make progress on a fix?

Taking some time to dig into how [sass-loader](https://github.com/jtangelder/sass-loader) implements resolving files from `@import`, it looks like sass-loader implements a custom importer, then uses that with `node-sass` to resolve `@import` files, and then finally adds the additional files to webpack.
1. https://github.com/jtangelder/sass-loader/blob/master/index.js#L85
2. https://github.com/jtangelder/sass-loader/blob/master/index.js#L242
3. https://github.com/jtangelder/sass-loader/blob/master/index.js#L252

**Comment by dmachat** [comment]
hey @ypt I haven't had a chance to dig into this one. if you want to take a swing at it, let me know. Otherwise I may have a chance at the end of this week.

**Comment by ypt** [comment]
Thanks @dmachat, I'll let you know if I give it a shot. Otherwise, thank you for looking into this!

**Comment by dmachat** [comment]
Due to complications handling sass import trees at the webpack loader level, we've forked this as a plugin: github.com/alleyinteractive/sasslint-webpack-plugin
