### ISSUE TITLE
Add default configFile path

### ISSUE THREAD

**Issue by zallek** [alleyinteractive/sasslint-loader#8]
Could be great if configFile option was set by default on `.sass-lint.yml` like done for sass-lint CLI.

Otherwise great loader :)

**Comment by jackmarketon** [comment]
Hey @zallek,
There is a little lack of documentation (we are working on it), you don't need to set the .sass-lint.yml
It should use `.sass-lint.yml` by default.

So you do not have to set:

```
sasslint: {
  configFile: '.sass-lint.yml'
}
```

In your webpack config.
